// Package grpcserver implements the AgentService that the Control Plane uses
// to manage VMs on this node.
package grpcserver

import (
	"context"
	"errors"
	"log/slog"

	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"

	"github.com/tuna2134/vps/internal/agent/libvirt"
	"github.com/tuna2134/vps/internal/agent/manager"
	"github.com/tuna2134/vps/internal/agent/metrics"

	agentv1 "github.com/tuna2134/vps/proto/gen/agent/v1"
	commonv1 "github.com/tuna2134/vps/proto/gen/common/v1"
)

// Server implements agentv1.AgentServiceServer.
type Server struct {
	agentv1.UnimplementedAgentServiceServer
	manager *manager.Manager
	libvirt libvirt.Manager
	metrics *metrics.Provider
	log     *slog.Logger
	// FakeMode is enabled for tests/dev where no real hypervisor exists.
	FakeMode bool
}

// New builds the agent gRPC server.
func New(mgr *manager.Manager, lv libvirt.Manager, metricsProvider *metrics.Provider, log *slog.Logger, fake bool) *Server {
	s := &Server{
		manager:  mgr,
		libvirt:  lv,
		metrics:  metricsProvider,
		log:      log,
		FakeMode: fake,
	}
	if mgr != nil {
		s.metrics.SetStoragePool(mgr.DefaultPool())
	}
	return s
}

func okResponse() *agentv1.OperationResponse {
	return &agentv1.OperationResponse{State: commonv1.OperationState_OPERATION_STATE_SUCCEEDED}
}

func errResponse(err error) *agentv1.OperationResponse {
	return &agentv1.OperationResponse{
		State: commonv1.OperationState_OPERATION_STATE_FAILED,
		Error: &commonv1.Error{Code: "AGENT_ERROR", Message: err.Error()},
	}
}

func (s *Server) CreateVM(ctx context.Context, req *agentv1.CreateVMRequest) (*agentv1.OperationResponse, error) {
	if s.FakeMode {
		return okResponse(), nil
	}
	if err := s.manager.CreateVM(ctx, req); err != nil {
		s.log.Error("create vm failed", "vm", req.GetVmId(), "error", err)
		return errResponse(err), nil
	}
	return okResponse(), nil
}

func (s *Server) DeleteVM(ctx context.Context, req *agentv1.DeleteVMRequest) (*agentv1.OperationResponse, error) {
	if s.FakeMode {
		return okResponse(), nil
	}
	if err := s.manager.DeleteVM(ctx, req); err != nil {
		s.log.Error("delete vm failed", "vm", req.GetVmId(), "error", err)
		return errResponse(err), nil
	}
	return okResponse(), nil
}

func (s *Server) StartVM(ctx context.Context, req *agentv1.StartVMRequest) (*agentv1.OperationResponse, error) {
	if s.FakeMode {
		return okResponse(), nil
	}
	if err := s.libvirt.StartDomain(vmName(req)); err != nil {
		return errResponse(err), nil
	}
	return okResponse(), nil
}

func (s *Server) StopVM(ctx context.Context, req *agentv1.StopVMRequest) (*agentv1.OperationResponse, error) {
	if s.FakeMode {
		return okResponse(), nil
	}
	if err := s.libvirt.ShutdownDomain(vmName(req)); err != nil {
		return errResponse(err), nil
	}
	return okResponse(), nil
}

func (s *Server) ForceStopVM(ctx context.Context, req *agentv1.ForceStopVMRequest) (*agentv1.OperationResponse, error) {
	if s.FakeMode {
		return okResponse(), nil
	}
	if err := s.libvirt.DestroyDomain(vmName(req)); err != nil {
		return errResponse(err), nil
	}
	return okResponse(), nil
}

func (s *Server) RebootVM(ctx context.Context, req *agentv1.RebootVMRequest) (*agentv1.OperationResponse, error) {
	if s.FakeMode {
		return okResponse(), nil
	}
	if err := s.libvirt.RebootDomain(vmName(req)); err != nil {
		return errResponse(err), nil
	}
	return okResponse(), nil
}

func (s *Server) GetVM(ctx context.Context, req *agentv1.GetVMRequest) (*agentv1.VMResponse, error) {
	if s.FakeMode {
		return &agentv1.VMResponse{Status: &commonv1.VMStatus{
			Name:  req.GetVmName(),
			Uuid:  req.GetVmId(),
			State: commonv1.VMState_VM_STATE_RUNNING,
		}}, nil
	}
	vmStatus, err := s.manager.GetVM(ctx, req)
	if err != nil {
		return nil, status.Error(codes.NotFound, "vm not found: "+err.Error())
	}
	return &agentv1.VMResponse{Status: vmStatus}, nil
}

func (s *Server) GetNodeStatus(ctx context.Context, req *agentv1.GetNodeStatusRequest) (*agentv1.NodeStatusResponse, error) {
	snap, err := s.snapshot()
	if err != nil {
		return nil, status.Error(codes.Internal, err.Error())
	}
	return &agentv1.NodeStatusResponse{Status: snapshotToProto(snap)}, nil
}

func (s *Server) Heartbeat(ctx context.Context, req *agentv1.HeartbeatRequest) (*agentv1.HeartbeatResponse, error) {
	snap, err := s.snapshot()
	if err != nil {
		return &agentv1.HeartbeatResponse{Ok: false}, nil
	}
	return &agentv1.HeartbeatResponse{Ok: snap.Healthy}, nil
}

func (s *Server) GetConsoleToken(ctx context.Context, req *agentv1.GetConsoleTokenRequest) (*agentv1.GetConsoleTokenResponse, error) {
	if s.FakeMode {
		return &agentv1.GetConsoleTokenResponse{Host: "127.0.0.1", Port: 5900, Token: "fake-token"}, nil
	}
	host, port, err := s.libvirt.GetVNCInfo(vmName(req))
	if err != nil {
		return nil, status.Error(codes.NotFound, "vnc console unavailable: "+err.Error())
	}
	// The token is generated by the Control Plane; the agent returns the
	// endpoint it will allow access to.
	return &agentv1.GetConsoleTokenResponse{Host: host, Port: uint32(port)}, nil
}

func (s *Server) snapshot() (*metrics.Snapshot, error) {
	return s.metrics.Sample()
}

func snapshotToProto(snap *metrics.Snapshot) *commonv1.NodeStatus {
	return &commonv1.NodeStatus{
		Hostname:          snap.Hostname,
		CpuCount:          uint32(snap.CPUCount),
		MemoryTotalBytes:  uint64(snap.MemoryTotalBytes),
		MemoryFreeBytes:   uint64(snap.MemoryFreeBytes),
		StorageTotalBytes: uint64(snap.StorageTotalBytes),
		StorageFreeBytes:  uint64(snap.StorageFreeBytes),
		CpuUsagePercent:   float32(snap.CPUUsagePercent),
		Healthy:           snap.Healthy,
	}
}

// vmName resolves the domain name from a request (mirrors control plane).
func vmName[T interface {
	GetVmId() string
	GetVmName() string
}](req T) string {
	if n := req.GetVmName(); n != "" {
		return n
	}
	return "vps-" + req.GetVmId()
}

var _ = errors.New
